# Generated by Django 5.2.17 on 2026-10-02 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('tasks', '0002_timelog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(choices=[('created', 'Creación'), ('updated', 'Edición'), ('status', 'Cambio de estado'), ('deleted', 'Eliminación'), ('member', 'Equipo'), ('subtask', 'Subtareas'), ('comment', 'Comentarios'), ('file', 'Archivos'), ('hours', 'Horas')], max_length=20)),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='projects.project')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='tasks.task')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividad',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['project', '-created_at'], name='activity_ac_project_0d9dc1_idx'), models.Index(fields=['task', '-created_at'], name='activity_ac_task_id_7a5790_idx')],
            },
        ),
    ]
