# Generated by Django 5.2.17 on 2026-10-01 19:50

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha')),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('24'))], verbose_name='Horas')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_logs', to='tasks.task')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de horas',
                'verbose_name_plural': 'Registros de horas',
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['task', 'date'], name='tasks_timel_task_id_a540d6_idx'), models.Index(fields=['user', 'date'], name='tasks_timel_user_id_9752ac_idx')],
            },
        ),
    ]
